#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void the_alarm_control_thread_deliver 
    (__po_hi_request_t* request);

void* the_alarm_control_thread_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
