#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE controller_k

#define __po_hi_the_alarm_control_thread_nb_ports 2

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  controller_k = 0
} __po_hi_node_t;

typedef enum
{
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  controller_the_video_thread_k_entity = 12,
  controller_the_door_sensor_thread_k_entity = 13,
  controller_the_window_sensor_thread_k_entity = 14,
  controller_the_pin_device_thread_k_entity = 15,
  controller_the_movement_sensor_thread_k_entity = 16,
  controller_the_access_control_thread_k_entity = 17,
  controller_the_alarm_control_thread_k_entity = 18
} __po_hi_entity_t;

typedef enum
{
  controller_the_alarm_control_thread_k = 0,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1,
  bus_mem_bus = 2,
  bus_mem_bus = 3
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 1

#define __PO_HI_TASKS_STACK 0

#define __PO_HI_NB_PROTECTED 0

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 19

#define __PO_HI_NB_PORTS 44

typedef enum
{
  the_video_thread_global_video_stream = 28,
  the_video_thread_global_person_on_video_detected = 29,
  the_door_sensor_thread_global_door_state = 30,
  the_door_sensor_thread_global_person_entered = 31,
  the_window_sensor_thread_global_window_state = 32,
  the_window_sensor_thread_global_window_opened = 33,
  the_pin_device_thread_global_entered_pin = 34,
  the_pin_device_thread_global_is_pin_correct = 35,
  the_movement_sensor_thread_global_movement_data = 36,
  the_movement_sensor_thread_global_person_in_room = 37,
  the_access_control_thread_global_is_pin_correct = 38,
  the_access_control_thread_global_person_on_video_detected = 39,
  the_access_control_thread_global_person_entered = 40,
  the_access_control_thread_global_access_type = 41,
  constant_out_identifier = 43,
  the_alarm_control_thread_global_access_type = 42,
  the_alarm_control_thread_global_turn_on_alarm = 43,
  constant_out_identifier = 45
} __po_hi_port_t;

typedef enum
{
  the_video_thread_local_video_stream = 0,
  the_video_thread_local_person_on_video_detected = 1,
  the_door_sensor_thread_local_door_state = 0,
  the_door_sensor_thread_local_person_entered = 1,
  the_window_sensor_thread_local_window_state = 0,
  the_window_sensor_thread_local_window_opened = 1,
  the_pin_device_thread_local_entered_pin = 0,
  the_pin_device_thread_local_is_pin_correct = 1,
  the_movement_sensor_thread_local_movement_data = 0,
  the_movement_sensor_thread_local_person_in_room = 1,
  the_access_control_thread_local_is_pin_correct = 0,
  the_access_control_thread_local_person_on_video_detected = 1,
  the_access_control_thread_local_person_entered = 2,
  the_access_control_thread_local_access_type = 3,
  the_alarm_control_thread_local_access_type = 0,
  the_alarm_control_thread_local_turn_on_alarm = 1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 4

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_the_alarm_control_thread_nb_ports

#endif
