/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void room_controller_alarm_control_thread 
    (threads__access_type access_type,
    threads__booleanvalue* turn_on_alarm);
void threads__alarm_control_spg 
    (threads__access_type access_type,
    threads__booleanvalue* turn_on_alarm)
{

  room_controller_alarm_control_thread (access_type, turn_on_alarm);
}


