#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"the_video_thread_global_video_stream","the_video_thread_global_person_on_video_detected","the_door_sensor_thread_global_door_state","the_door_sensor_thread_global_person_entered","the_window_sensor_thread_global_window_state","the_window_sensor_thread_global_window_opened","the_pin_device_thread_global_entered_pin","the_pin_device_thread_global_is_pin_correct","the_movement_sensor_thread_global_movement_data","the_movement_sensor_thread_global_person_in_room","the_access_control_thread_global_is_pin_correct","the_access_control_thread_global_person_on_video_detected","the_access_control_thread_global_person_entered","the_access_control_thread_global_access_type","the_alarm_control_thread_global_access_type","the_alarm_control_thread_global_turn_on_alarm"};

