#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void roomcontroller_alarmcontrolthread 
    (threads__access_type access_type,
    threads__booleanvalue* turn_on_alarm);
void threads__alarm_control_spg 
    (threads__access_type access_type,
    threads__booleanvalue* turn_on_alarm)
{

  roomcontroller_alarmcontrolthread (access_type, turn_on_alarm);
}


