--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated.Activity;
with PolyORB_HI.Messages;
with PolyORB_HI_Generated.Types;

package PolyORB_HI_Generated.Marshallers is

  --  Marshallers for interface type of thread video_thread.i

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.threads_video_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.threads_video_thread_i_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.threads_video_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type video_stream

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Video_Stream;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Video_Stream;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type booleanvalue

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.BooleanValue;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.BooleanValue;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread door_sensor_thread.i

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.threads_door_sensor_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.threads_door_sensor_thread_i_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.threads_door_sensor_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type door_state

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Door_State;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Door_State;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread window_sensor_thread.i

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.threads_window_sensor_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.threads_window_sensor_thread_i_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.threads_window_sensor_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type window_state

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Window_State;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Window_State;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread pin_device_thread.i

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.threads_pin_device_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.threads_pin_device_thread_i_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.threads_pin_device_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type pin

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Pin;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Pin;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread movement_sensor_thread.i

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.threads_movement_sensor_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.threads_movement_sensor_thread_i_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.threads_movement_sensor_thread_i_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread access_control_thread.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.threads_access_control_thread_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.threads_access_control_thread_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.threads_access_control_thread_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type access_type

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Access_Type;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Access_Type;
    Message : in out PolyORB_HI.Messages.Message_Type);

end PolyORB_HI_Generated.Marshallers;
