#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void the_video_thread_deliver 
    (__po_hi_request_t* request);

void* the_video_thread_job (void);

void the_door_sensor_thread_deliver 
    (__po_hi_request_t* request);

void* the_door_sensor_thread_job (void);

void the_window_sensor_thread_deliver 
    (__po_hi_request_t* request);

void* the_window_sensor_thread_job (void);

void the_pin_device_thread_deliver 
    (__po_hi_request_t* request);

void* the_pin_device_thread_job (void);

void the_movement_sensor_thread_deliver 
    (__po_hi_request_t* request);

void* the_movement_sensor_thread_job (void);

void the_access_control_thread_deliver 
    (__po_hi_request_t* request);

void* the_access_control_thread_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
