#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
#include <types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void threads__video_processing_spg 
    (threads__video_stream video_stream,
    threads__booleanvalue* person_on_video_detected);

void threads__door_sensor_spg 
    (threads__door_state door_state,
    threads__booleanvalue* door_opened);

void threads__window_sensor_spg 
    (threads__window_state window_state,
    threads__booleanvalue* window_opened);

void threads__pin_device_spg 
    (threads__pin entered_pin,
    threads__booleanvalue* is_pin_correct);

void threads__movement_sensor_spg 
    (threads__booleanvalue movement_data,
    threads__booleanvalue* person_in_room);

void threads__access_control_spg 
    (threads__booleanvalue is_pin_correct,
    threads__booleanvalue person_on_video_detected,
    threads__booleanvalue person_entered,
    threads__access_type* access_type);

#endif
