--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Deployment is

  pragma Preelaborate;

  --  For each node in the distributed application add an enumerator

  type Node_Type is
   (standard_room_controller_K);

  --  Representation clause to have consistent positions for enumerators

  for Node_Type use
   (standard_room_controller_K =>
     1);

  --  Size of Node_Type fixed to 8 bits

  for Node_Type'Size use 8;

  Max_Node_Image_Size : constant Standard.Integer :=
   26;

  --  Maximal Node_Image size for this node

  --  Node Image

  subtype UT_Deployment_Standard_Room_Controller_Node_Type_Range is
   Node_Type range Node_Type'First .. Node_Type'Last;

  subtype UT_Deployment_Standard_Room_Controller_1_Max_Node_Image_Size is
   Integer range 1 .. Max_Node_Image_Size;

  subtype UT_Deployment_Standard_Room_Controller_Node_Image_Component is
   Standard.String
     (UT_Deployment_Standard_Room_Controller_1_Max_Node_Image_Size);

  type UT_Deployment_Standard_Room_Controller_Node_Image_Array is
   array (UT_Deployment_Standard_Room_Controller_Node_Type_Range)
     of UT_Deployment_Standard_Room_Controller_Node_Image_Component;

  Node_Image : constant UT_Deployment_Standard_Room_Controller_Node_Image_Array :=
   UT_Deployment_Standard_Room_Controller_Node_Image_Array'
     (standard_room_controller_K =>
       "standard_room_controller_K");

  My_Node : constant Node_Type :=
   standard_room_controller_K;

  --  For each thread in the distributed application nodes, add an enumerator

  type Entity_Type is
   (standard_room_controller_the_video_thread_K,
    standard_room_controller_the_door_sensor_thread_K,
    standard_room_controller_the_window_sensor_thread_K,
    standard_room_controller_the_pin_device_thread_K,
    standard_room_controller_the_movement_sensor_thread_K,
    standard_room_controller_the_access_control_thread_K);

  --  Representation clause to have consistent positions for enumerators

  for Entity_Type use
   (standard_room_controller_the_video_thread_K =>
     1,
    standard_room_controller_the_door_sensor_thread_K =>
     2,
    standard_room_controller_the_window_sensor_thread_K =>
     3,
    standard_room_controller_the_pin_device_thread_K =>
     4,
    standard_room_controller_the_movement_sensor_thread_K =>
     5,
    standard_room_controller_the_access_control_thread_K =>
     6);

  --  Size of Entity_Type fixed to 8 bits

  for Entity_Type'Size use 8;

  --  Entity Table

  subtype UT_Deployment_Standard_Room_Controller_Entity_Type_Range is
   Entity_Type range Entity_Type'First .. Entity_Type'Last;

  type UT_Deployment_Standard_Room_Controller_Entity_Table_Array is
   array (UT_Deployment_Standard_Room_Controller_Entity_Type_Range)
     of Node_Type;

  Entity_Table : constant UT_Deployment_Standard_Room_Controller_Entity_Table_Array :=
   UT_Deployment_Standard_Room_Controller_Entity_Table_Array'
     (standard_room_controller_the_video_thread_K =>
       standard_room_controller_K,
      standard_room_controller_the_door_sensor_thread_K =>
       standard_room_controller_K,
      standard_room_controller_the_window_sensor_thread_K =>
       standard_room_controller_K,
      standard_room_controller_the_pin_device_thread_K =>
       standard_room_controller_K,
      standard_room_controller_the_movement_sensor_thread_K =>
       standard_room_controller_K,
      standard_room_controller_the_access_control_thread_K =>
       standard_room_controller_K);

  Max_Entity_Image_Size : constant Standard.Integer :=
   53;

  --  Maximal Entity_Image size for this node

  --  Entity Image

  subtype UT_Deployment_Standard_Room_Controller_1_Max_Entity_Image_Size is
   Integer range 1 .. Max_Entity_Image_Size;

  subtype UT_Deployment_Standard_Room_Controller_Entity_Image_Component is
   Standard.String
     (UT_Deployment_Standard_Room_Controller_1_Max_Entity_Image_Size);

  type UT_Deployment_Standard_Room_Controller_Entity_Image_Array is
   array (UT_Deployment_Standard_Room_Controller_Entity_Type_Range)
     of UT_Deployment_Standard_Room_Controller_Entity_Image_Component;

  Entity_Image : constant UT_Deployment_Standard_Room_Controller_Entity_Image_Array :=
   UT_Deployment_Standard_Room_Controller_Entity_Image_Array'
     (standard_room_controller_the_video_thread_K =>
       "standard_room_controller_the_video_thread_K          ",
      standard_room_controller_the_door_sensor_thread_K =>
       "standard_room_controller_the_door_sensor_thread_K    ",
      standard_room_controller_the_window_sensor_thread_K =>
       "standard_room_controller_the_window_sensor_thread_K  ",
      standard_room_controller_the_pin_device_thread_K =>
       "standard_room_controller_the_pin_device_thread_K     ",
      standard_room_controller_the_movement_sensor_thread_K =>
       "standard_room_controller_the_movement_sensor_thread_K",
      standard_room_controller_the_access_control_thread_K =>
       "standard_room_controller_the_access_control_thread_K ");

  --  For each thread port in the distributed application nodes, add an 
  --  enumerator

  type Port_Type is
   (standard_room_controller_the_video_thread_video_stream_K,
    standard_room_controller_the_video_thread_person_on_video_detected_K,
    standard_room_controller_the_door_sensor_thread_door_state_K,
    standard_room_controller_the_door_sensor_thread_person_entered_K,
    standard_room_controller_the_window_sensor_thread_window_state_K,
    standard_room_controller_the_window_sensor_thread_window_opened_K,
    standard_room_controller_the_pin_device_thread_entered_pin_K,
    standard_room_controller_the_pin_device_thread_is_pin_correct_K,
    standard_room_controller_the_movement_sensor_thread_movement_data_K,
    standard_room_controller_the_movement_sensor_thread_person_in_room_K,
    standard_room_controller_the_access_control_thread_is_pin_correct_K,
    standard_room_controller_the_access_control_thread_person_on_video_detected_K,
    standard_room_controller_the_access_control_thread_person_entered_K,
    standard_room_controller_the_access_control_thread_access_type_K);

  --  Representation clause to have consistent positions for enumerators

  for Port_Type use
   (standard_room_controller_the_video_thread_video_stream_K =>
     1,
    standard_room_controller_the_video_thread_person_on_video_detected_K =>
     2,
    standard_room_controller_the_door_sensor_thread_door_state_K =>
     3,
    standard_room_controller_the_door_sensor_thread_person_entered_K =>
     4,
    standard_room_controller_the_window_sensor_thread_window_state_K =>
     5,
    standard_room_controller_the_window_sensor_thread_window_opened_K =>
     6,
    standard_room_controller_the_pin_device_thread_entered_pin_K =>
     7,
    standard_room_controller_the_pin_device_thread_is_pin_correct_K =>
     8,
    standard_room_controller_the_movement_sensor_thread_movement_data_K =>
     9,
    standard_room_controller_the_movement_sensor_thread_person_in_room_K =>
     10,
    standard_room_controller_the_access_control_thread_is_pin_correct_K =>
     11,
    standard_room_controller_the_access_control_thread_person_on_video_detected_K =>
     12,
    standard_room_controller_the_access_control_thread_person_entered_K =>
     13,
    standard_room_controller_the_access_control_thread_access_type_K =>
     14);

  --  Size of Port_Type fixed to 16 bits

  for Port_Type'Size use 16;

  --  Port Table

  subtype UT_Deployment_Standard_Room_Controller_Port_Type_Range is
   Port_Type range Port_Type'First .. Port_Type'Last;

  type UT_Deployment_Standard_Room_Controller_Port_Table_Array is
   array (UT_Deployment_Standard_Room_Controller_Port_Type_Range)
     of Entity_Type;

  Port_Table : constant UT_Deployment_Standard_Room_Controller_Port_Table_Array :=
   UT_Deployment_Standard_Room_Controller_Port_Table_Array'
     (standard_room_controller_the_video_thread_video_stream_K =>
       standard_room_controller_the_video_thread_K,
      standard_room_controller_the_video_thread_person_on_video_detected_K =>
       standard_room_controller_the_video_thread_K,
      standard_room_controller_the_door_sensor_thread_door_state_K =>
       standard_room_controller_the_door_sensor_thread_K,
      standard_room_controller_the_door_sensor_thread_person_entered_K =>
       standard_room_controller_the_door_sensor_thread_K,
      standard_room_controller_the_window_sensor_thread_window_state_K =>
       standard_room_controller_the_window_sensor_thread_K,
      standard_room_controller_the_window_sensor_thread_window_opened_K =>
       standard_room_controller_the_window_sensor_thread_K,
      standard_room_controller_the_pin_device_thread_entered_pin_K =>
       standard_room_controller_the_pin_device_thread_K,
      standard_room_controller_the_pin_device_thread_is_pin_correct_K =>
       standard_room_controller_the_pin_device_thread_K,
      standard_room_controller_the_movement_sensor_thread_movement_data_K =>
       standard_room_controller_the_movement_sensor_thread_K,
      standard_room_controller_the_movement_sensor_thread_person_in_room_K =>
       standard_room_controller_the_movement_sensor_thread_K,
      standard_room_controller_the_access_control_thread_is_pin_correct_K =>
       standard_room_controller_the_access_control_thread_K,
      standard_room_controller_the_access_control_thread_person_on_video_detected_K =>
       standard_room_controller_the_access_control_thread_K,
      standard_room_controller_the_access_control_thread_person_entered_K =>
       standard_room_controller_the_access_control_thread_K,
      standard_room_controller_the_access_control_thread_access_type_K =>
       standard_room_controller_the_access_control_thread_K);

  Max_Port_Image_Size : constant Standard.Integer :=
   77;

  --  Maximal Port_Image size for this node

  subtype Port_Sized_String is
   Standard.String
     (1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size);

  --  Port Image

  type UT_Deployment_Standard_Room_Controller_Port_Image_Array is
   array (UT_Deployment_Standard_Room_Controller_Port_Type_Range)
     of Port_Sized_String;

  Port_Image : constant UT_Deployment_Standard_Room_Controller_Port_Image_Array :=
   UT_Deployment_Standard_Room_Controller_Port_Image_Array'
     (standard_room_controller_the_video_thread_video_stream_K =>
       "standard_room_controller_the_video_thread_video_stream_K                     ",
      standard_room_controller_the_video_thread_person_on_video_detected_K =>
       "standard_room_controller_the_video_thread_person_on_video_detected_K         ",
      standard_room_controller_the_door_sensor_thread_door_state_K =>
       "standard_room_controller_the_door_sensor_thread_door_state_K                 ",
      standard_room_controller_the_door_sensor_thread_person_entered_K =>
       "standard_room_controller_the_door_sensor_thread_person_entered_K             ",
      standard_room_controller_the_window_sensor_thread_window_state_K =>
       "standard_room_controller_the_window_sensor_thread_window_state_K             ",
      standard_room_controller_the_window_sensor_thread_window_opened_K =>
       "standard_room_controller_the_window_sensor_thread_window_opened_K            ",
      standard_room_controller_the_pin_device_thread_entered_pin_K =>
       "standard_room_controller_the_pin_device_thread_entered_pin_K                 ",
      standard_room_controller_the_pin_device_thread_is_pin_correct_K =>
       "standard_room_controller_the_pin_device_thread_is_pin_correct_K              ",
      standard_room_controller_the_movement_sensor_thread_movement_data_K =>
       "standard_room_controller_the_movement_sensor_thread_movement_data_K          ",
      standard_room_controller_the_movement_sensor_thread_person_in_room_K =>
       "standard_room_controller_the_movement_sensor_thread_person_in_room_K         ",
      standard_room_controller_the_access_control_thread_is_pin_correct_K =>
       "standard_room_controller_the_access_control_thread_is_pin_correct_K          ",
      standard_room_controller_the_access_control_thread_person_on_video_detected_K =>
       "standard_room_controller_the_access_control_thread_person_on_video_detected_K",
      standard_room_controller_the_access_control_thread_person_entered_K =>
       "standard_room_controller_the_access_control_thread_person_entered_K          ",
      standard_room_controller_the_access_control_thread_access_type_K =>
       "standard_room_controller_the_access_control_thread_access_type_K             ");

  --  Maximal message payload size for this node (in bits)

  Max_Payload_Size : constant Standard.Integer :=
   112;

  --  Biggest type: video_stream

end PolyORB_HI_Generated.Deployment;
