--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type Video_Stream is
   new Standard.Integer;

  --  video_stream'Object_Size ~= 32 bits

  Video_Stream_Default_Value : constant Video_Stream :=
   0;

  type BooleanValue is
   new Standard.Integer;

  --  booleanvalue'Object_Size ~= 32 bits

  BooleanValue_Default_Value : constant BooleanValue :=
   0;

  type Door_State is
   new Standard.Integer;

  --  door_state'Object_Size ~= 32 bits

  Door_State_Default_Value : constant Door_State :=
   0;

  type Window_State is
   new Standard.Integer;

  --  window_state'Object_Size ~= 32 bits

  Window_State_Default_Value : constant Window_State :=
   0;

  type Pin is
   new Standard.Integer;

  --  pin'Object_Size ~= 32 bits

  Pin_Default_Value : constant Pin :=
   0;

  type Access_Type is
   (authorized,
    unauthorized,
    no_person_in_room);

  --  access_type'Object_Size ~= 16 bits

  Access_Type_Default_Value : Access_Type;

end PolyORB_HI_Generated.Types;
