#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <types.h>
#include "subprograms.h"
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_the_alarm_control_thread_turn_on_alarm_local_destinations[1] = {alarm_global_turn_on_alarm};
__po_hi_uint8_t __po_hi_the_alarm_control_thread_woffsets[__po_hi_the_alarm_control_thread_nb_ports];
__po_hi_uint8_t __po_hi_the_alarm_control_thread_offsets[__po_hi_the_alarm_control_thread_nb_ports];
__po_hi_uint8_t __po_hi_the_alarm_control_thread_used_size[__po_hi_the_alarm_control_thread_nb_ports];
__po_hi_uint8_t __po_hi_the_alarm_control_thread_empties[__po_hi_the_alarm_control_thread_nb_ports];
__po_hi_uint8_t __po_hi_the_alarm_control_thread_first[__po_hi_the_alarm_control_thread_nb_ports];
__po_hi_request_t __po_hi_the_alarm_control_thread_recent[__po_hi_the_alarm_control_thread_nb_ports];
__po_hi_port_t __po_hi_the_alarm_control_thread_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_alarm_control_thread_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_alarm_control_thread_history[0];
__po_hi_uint8_t __po_hi_the_alarm_control_thread_n_dest[__po_hi_the_alarm_control_thread_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_the_alarm_control_thread_fifo_size[__po_hi_the_alarm_control_thread_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_alarm_control_thread_destinations[__po_hi_the_alarm_control_thread_nb_ports] = {NULL,__po_hi_the_alarm_control_thread_turn_on_alarm_local_destinations};

/*!
 * \fn void the_alarm_control_thread_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_alarm_control_thread
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_alarm_control_thread_deliver) stores the incoming request for the 
 * taskthe_alarm_control_thread
 */
void the_alarm_control_thread_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_alarm_control_thread_global_access_type:
    {
      __po_hi_gqueue_store_in (global_controller_the_alarm_control_thread_k, the_alarm_control_thread_local_access_type, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_alarm_control_thread_job (void)
 * \brief Function executed by the task the_alarm_control_thread
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_alarm_control_thread*/
/*  Get the IN ports values*/
void* the_alarm_control_thread_job (void)
{
  __po_hi_request_t static access_type_request;
  threads__booleanvalue turn_on_alarm_request_var;
  __po_hi_request_t turn_on_alarm_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (global_controller_the_alarm_control_thread_k, __po_hi_the_alarm_control_thread_nb_ports, __po_hi_the_alarm_control_thread_queue, __po_hi_the_alarm_control_thread_fifo_size, __po_hi_the_alarm_control_thread_first, __po_hi_the_alarm_control_thread_offsets, __po_hi_the_alarm_control_thread_woffsets, __po_hi_the_alarm_control_thread_n_dest, __po_hi_the_alarm_control_thread_destinations, __po_hi_the_alarm_control_thread_used_size, __po_hi_the_alarm_control_thread_history, __po_hi_the_alarm_control_thread_recent, __po_hi_the_alarm_control_thread_empties, __po_hi_the_alarm_control_thread_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (global_controller_the_alarm_control_thread_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (global_controller_the_alarm_control_thread_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (global_controller_the_alarm_control_thread_k, the_alarm_control_thread_local_access_type))
    {
          __po_hi_gqueue_get_value (global_controller_the_alarm_control_thread_k, the_alarm_control_thread_local_access_type, &(access_type_request));
      __po_hi_gqueue_next_value (global_controller_the_alarm_control_thread_k, the_alarm_control_thread_local_access_type);

    }
    /*  Call implementation*/
    threads__alarm_control_spg (access_type_request.vars.the_alarm_control_thread_global_access_type.the_alarm_control_thread_global_access_type, &(turn_on_alarm_request_var));
    /*  Set the OUT port values*/
    turn_on_alarm_request.vars.the_alarm_control_thread_global_turn_on_alarm.the_alarm_control_thread_global_turn_on_alarm = turn_on_alarm_request_var;
    turn_on_alarm_request.port = the_alarm_control_thread_global_turn_on_alarm;
    __po_hi_gqueue_store_out (global_controller_the_alarm_control_thread_k, the_alarm_control_thread_local_turn_on_alarm, &(turn_on_alarm_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (global_controller_the_alarm_control_thread_k, the_alarm_control_thread_global_turn_on_alarm);
    __po_hi_wait_for_next_period (global_controller_the_alarm_control_thread_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case global_controller_the_alarm_control_thread_k_entity:
    {
      the_alarm_control_thread_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


