#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_access_type 
    (threads__access_type value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int32 (value, message, offset);
}

void __po_hi_unmarshall_type_access_type 
    (threads__access_type* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int32 ((__po_hi_int32_t*)value, message, offset);
}

void __po_hi_marshall_type_booleanvalue 
    (threads__booleanvalue value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_booleanvalue 
    (threads__booleanvalue* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_request_the_alarm_control_thread_access_type 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_access_type (request->vars.the_alarm_control_thread_global_access_type.the_alarm_control_thread_global_access_type, message, offset);
}

void __po_hi_unmarshall_request_the_alarm_control_thread_access_type 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_access_type (&(request->vars.the_alarm_control_thread_global_access_type.the_alarm_control_thread_global_access_type), message, offset);
}

void __po_hi_marshall_request_the_alarm_control_thread_turn_on_alarm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_alarm_control_thread_global_turn_on_alarm.the_alarm_control_thread_global_turn_on_alarm, message, offset);
}

void __po_hi_unmarshall_request_the_alarm_control_thread_turn_on_alarm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_alarm_control_thread_global_turn_on_alarm.the_alarm_control_thread_global_turn_on_alarm), message, offset);
}

void __po_hi_marshall_type_door_state 
    (threads__door_state value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_door_state 
    (threads__door_state* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_type_window_state 
    (threads__window_state value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_window_state 
    (threads__window_state* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_type_video_stream 
    (threads__video_stream value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_video_stream 
    (threads__video_stream* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_type_pin 
    (threads__pin value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_pin 
    (threads__pin* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_request_the_video_thread_video_stream 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_video_stream (request->vars.the_video_thread_global_video_stream.the_video_thread_global_video_stream, message, offset);
}

void __po_hi_unmarshall_request_the_video_thread_video_stream 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_video_stream (&(request->vars.the_video_thread_global_video_stream.the_video_thread_global_video_stream), message, offset);
}

void __po_hi_marshall_request_the_video_thread_person_on_video_detected 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_video_thread_global_person_on_video_detected.the_video_thread_global_person_on_video_detected, message, offset);
}

void __po_hi_unmarshall_request_the_video_thread_person_on_video_detected 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_video_thread_global_person_on_video_detected.the_video_thread_global_person_on_video_detected), message, offset);
}

void __po_hi_marshall_request_the_door_sensor_thread_door_state 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_door_state (request->vars.the_door_sensor_thread_global_door_state.the_door_sensor_thread_global_door_state, message, offset);
}

void __po_hi_unmarshall_request_the_door_sensor_thread_door_state 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_door_state (&(request->vars.the_door_sensor_thread_global_door_state.the_door_sensor_thread_global_door_state), message, offset);
}

void __po_hi_marshall_request_the_door_sensor_thread_person_entered 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_door_sensor_thread_global_person_entered.the_door_sensor_thread_global_person_entered, message, offset);
}

void __po_hi_unmarshall_request_the_door_sensor_thread_person_entered 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_door_sensor_thread_global_person_entered.the_door_sensor_thread_global_person_entered), message, offset);
}

void __po_hi_marshall_request_the_window_sensor_thread_window_state 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_window_state (request->vars.the_window_sensor_thread_global_window_state.the_window_sensor_thread_global_window_state, message, offset);
}

void __po_hi_unmarshall_request_the_window_sensor_thread_window_state 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_window_state (&(request->vars.the_window_sensor_thread_global_window_state.the_window_sensor_thread_global_window_state), message, offset);
}

void __po_hi_marshall_request_the_window_sensor_thread_window_opened 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_window_sensor_thread_global_window_opened.the_window_sensor_thread_global_window_opened, message, offset);
}

void __po_hi_unmarshall_request_the_window_sensor_thread_window_opened 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_window_sensor_thread_global_window_opened.the_window_sensor_thread_global_window_opened), message, offset);
}

void __po_hi_marshall_request_the_pin_device_thread_entered_pin 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_pin (request->vars.the_pin_device_thread_global_entered_pin.the_pin_device_thread_global_entered_pin, message, offset);
}

void __po_hi_unmarshall_request_the_pin_device_thread_entered_pin 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_pin (&(request->vars.the_pin_device_thread_global_entered_pin.the_pin_device_thread_global_entered_pin), message, offset);
}

void __po_hi_marshall_request_the_pin_device_thread_is_pin_correct 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_pin_device_thread_global_is_pin_correct.the_pin_device_thread_global_is_pin_correct, message, offset);
}

void __po_hi_unmarshall_request_the_pin_device_thread_is_pin_correct 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_pin_device_thread_global_is_pin_correct.the_pin_device_thread_global_is_pin_correct), message, offset);
}

void __po_hi_marshall_request_the_movement_sensor_thread_movement_data 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_movement_sensor_thread_global_movement_data.the_movement_sensor_thread_global_movement_data, message, offset);
}

void __po_hi_unmarshall_request_the_movement_sensor_thread_movement_data 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_movement_sensor_thread_global_movement_data.the_movement_sensor_thread_global_movement_data), message, offset);
}

void __po_hi_marshall_request_the_movement_sensor_thread_person_in_room 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_movement_sensor_thread_global_person_in_room.the_movement_sensor_thread_global_person_in_room, message, offset);
}

void __po_hi_unmarshall_request_the_movement_sensor_thread_person_in_room 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_movement_sensor_thread_global_person_in_room.the_movement_sensor_thread_global_person_in_room), message, offset);
}

void __po_hi_marshall_request_the_access_control_thread_is_pin_correct 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_access_control_thread_global_is_pin_correct.the_access_control_thread_global_is_pin_correct, message, offset);
}

void __po_hi_unmarshall_request_the_access_control_thread_is_pin_correct 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_access_control_thread_global_is_pin_correct.the_access_control_thread_global_is_pin_correct), message, offset);
}

void __po_hi_marshall_request_the_access_control_thread_person_on_video_detected 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_access_control_thread_global_person_on_video_detected.the_access_control_thread_global_person_on_video_detected, message, offset);
}

void __po_hi_unmarshall_request_the_access_control_thread_person_on_video_detected 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_access_control_thread_global_person_on_video_detected.the_access_control_thread_global_person_on_video_detected), message, offset);
}

void __po_hi_marshall_request_the_access_control_thread_person_entered 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_booleanvalue (request->vars.the_access_control_thread_global_person_entered.the_access_control_thread_global_person_entered, message, offset);
}

void __po_hi_unmarshall_request_the_access_control_thread_person_entered 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_booleanvalue (&(request->vars.the_access_control_thread_global_person_entered.the_access_control_thread_global_person_entered), message, offset);
}

void __po_hi_marshall_request_the_access_control_thread_access_type 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_access_type (request->vars.the_access_control_thread_global_access_type.the_access_control_thread_global_access_type, message, offset);
}

void __po_hi_unmarshall_request_the_access_control_thread_access_type 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_access_type (&(request->vars.the_access_control_thread_global_access_type.the_access_control_thread_global_access_type), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case the_alarm_control_thread_global_access_type:
    {
      __po_hi_marshall_request_the_alarm_control_thread_access_type (request, message, &(offset));

      break;
    }
    case the_alarm_control_thread_global_turn_on_alarm:
    {
      __po_hi_marshall_request_the_alarm_control_thread_turn_on_alarm (request, message, &(offset));

      break;
    }
    case the_video_thread_global_video_stream:
    {
      __po_hi_marshall_request_the_video_thread_video_stream (request, message, &(offset));

      break;
    }
    case the_video_thread_global_person_on_video_detected:
    {
      __po_hi_marshall_request_the_video_thread_person_on_video_detected (request, message, &(offset));

      break;
    }
    case the_door_sensor_thread_global_door_state:
    {
      __po_hi_marshall_request_the_door_sensor_thread_door_state (request, message, &(offset));

      break;
    }
    case the_door_sensor_thread_global_person_entered:
    {
      __po_hi_marshall_request_the_door_sensor_thread_person_entered (request, message, &(offset));

      break;
    }
    case the_window_sensor_thread_global_window_state:
    {
      __po_hi_marshall_request_the_window_sensor_thread_window_state (request, message, &(offset));

      break;
    }
    case the_window_sensor_thread_global_window_opened:
    {
      __po_hi_marshall_request_the_window_sensor_thread_window_opened (request, message, &(offset));

      break;
    }
    case the_pin_device_thread_global_entered_pin:
    {
      __po_hi_marshall_request_the_pin_device_thread_entered_pin (request, message, &(offset));

      break;
    }
    case the_pin_device_thread_global_is_pin_correct:
    {
      __po_hi_marshall_request_the_pin_device_thread_is_pin_correct (request, message, &(offset));

      break;
    }
    case the_movement_sensor_thread_global_movement_data:
    {
      __po_hi_marshall_request_the_movement_sensor_thread_movement_data (request, message, &(offset));

      break;
    }
    case the_movement_sensor_thread_global_person_in_room:
    {
      __po_hi_marshall_request_the_movement_sensor_thread_person_in_room (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_is_pin_correct:
    {
      __po_hi_marshall_request_the_access_control_thread_is_pin_correct (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_person_on_video_detected:
    {
      __po_hi_marshall_request_the_access_control_thread_person_on_video_detected (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_person_entered:
    {
      __po_hi_marshall_request_the_access_control_thread_person_entered (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_access_type:
    {
      __po_hi_marshall_request_the_access_control_thread_access_type (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case the_alarm_control_thread_global_access_type:
    {
      __po_hi_unmarshall_request_the_alarm_control_thread_access_type (request, message, &(offset));

      break;
    }
    case the_alarm_control_thread_global_turn_on_alarm:
    {
      __po_hi_unmarshall_request_the_alarm_control_thread_turn_on_alarm (request, message, &(offset));

      break;
    }
    case the_video_thread_global_video_stream:
    {
      __po_hi_unmarshall_request_the_video_thread_video_stream (request, message, &(offset));

      break;
    }
    case the_video_thread_global_person_on_video_detected:
    {
      __po_hi_unmarshall_request_the_video_thread_person_on_video_detected (request, message, &(offset));

      break;
    }
    case the_door_sensor_thread_global_door_state:
    {
      __po_hi_unmarshall_request_the_door_sensor_thread_door_state (request, message, &(offset));

      break;
    }
    case the_door_sensor_thread_global_person_entered:
    {
      __po_hi_unmarshall_request_the_door_sensor_thread_person_entered (request, message, &(offset));

      break;
    }
    case the_window_sensor_thread_global_window_state:
    {
      __po_hi_unmarshall_request_the_window_sensor_thread_window_state (request, message, &(offset));

      break;
    }
    case the_window_sensor_thread_global_window_opened:
    {
      __po_hi_unmarshall_request_the_window_sensor_thread_window_opened (request, message, &(offset));

      break;
    }
    case the_pin_device_thread_global_entered_pin:
    {
      __po_hi_unmarshall_request_the_pin_device_thread_entered_pin (request, message, &(offset));

      break;
    }
    case the_pin_device_thread_global_is_pin_correct:
    {
      __po_hi_unmarshall_request_the_pin_device_thread_is_pin_correct (request, message, &(offset));

      break;
    }
    case the_movement_sensor_thread_global_movement_data:
    {
      __po_hi_unmarshall_request_the_movement_sensor_thread_movement_data (request, message, &(offset));

      break;
    }
    case the_movement_sensor_thread_global_person_in_room:
    {
      __po_hi_unmarshall_request_the_movement_sensor_thread_person_in_room (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_is_pin_correct:
    {
      __po_hi_unmarshall_request_the_access_control_thread_is_pin_correct (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_person_on_video_detected:
    {
      __po_hi_unmarshall_request_the_access_control_thread_person_on_video_detected (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_person_entered:
    {
      __po_hi_unmarshall_request_the_access_control_thread_person_entered (request, message, &(offset));

      break;
    }
    case the_access_control_thread_global_access_type:
    {
      __po_hi_unmarshall_request_the_access_control_thread_access_type (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


