#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      threads__video_stream the_video_thread_global_video_stream;

    } the_video_thread_global_video_stream;

    struct
    {
      threads__booleanvalue the_video_thread_global_person_on_video_detected;

    } the_video_thread_global_person_on_video_detected;

    struct
    {
      threads__door_state the_door_sensor_thread_global_door_state;

    } the_door_sensor_thread_global_door_state;

    struct
    {
      threads__booleanvalue the_door_sensor_thread_global_person_entered;

    } the_door_sensor_thread_global_person_entered;

    struct
    {
      threads__window_state the_window_sensor_thread_global_window_state;

    } the_window_sensor_thread_global_window_state;

    struct
    {
      threads__booleanvalue the_window_sensor_thread_global_window_opened;

    } the_window_sensor_thread_global_window_opened;

    struct
    {
      threads__pin the_pin_device_thread_global_entered_pin;

    } the_pin_device_thread_global_entered_pin;

    struct
    {
      threads__booleanvalue the_pin_device_thread_global_is_pin_correct;

    } the_pin_device_thread_global_is_pin_correct;

    struct
    {
      threads__booleanvalue the_movement_sensor_thread_global_movement_data;

    } the_movement_sensor_thread_global_movement_data;

    struct
    {
      threads__booleanvalue the_movement_sensor_thread_global_person_in_room;

    } the_movement_sensor_thread_global_person_in_room;

    struct
    {
      threads__booleanvalue the_access_control_thread_global_is_pin_correct;

    } the_access_control_thread_global_is_pin_correct;

    struct
    {
      threads__booleanvalue the_access_control_thread_global_person_on_video_detected;

    } the_access_control_thread_global_person_on_video_detected;

    struct
    {
      threads__booleanvalue the_access_control_thread_global_person_entered;

    } the_access_control_thread_global_person_entered;

    struct
    {
      threads__access_type the_access_control_thread_global_access_type;

    } the_access_control_thread_global_access_type;

    struct
    {
      threads__access_type the_alarm_control_thread_global_access_type;

    } the_alarm_control_thread_global_access_type;

    struct
    {
      threads__booleanvalue the_alarm_control_thread_global_turn_on_alarm;

    } the_alarm_control_thread_global_turn_on_alarm;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
