#ifndef __OCARINA_GENERATED_TYPES_H_
#define __OCARINA_GENERATED_TYPES_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

typedef int threads__video_stream;

typedef int threads__booleanvalue;

typedef int threads__door_state;

typedef int threads__window_state;

typedef int threads__pin;

typedef enum
{
  access_typeaccess_type_authorized,
  access_typeaccess_type_unauthorized,
  access_typeaccess_type_no_person_in_room
} threads__access_type;

#endif
